In [69]:
import pandas as pd
df = pd.read_csv("Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [70]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

https://docs.google.com/spreadsheets/d/1XSKAglKkXLqDa08CAWUctKZzBaf7R5gRBCPm9alIIDw/edit#gid=0

#Q1. How many passengers survived?

In [71]:
df['Survived'].value_counts()[1]
survivors= df['Survived'].value_counts()[1]
print("Total survivors:" , survivors)

Total survivors: 342

#Q2. What was the survival rate for women vs men?

In [72]:
women = df.loc[df.Sex == 'female']["Survived"]
rate_women = round(sum(women)/len(women) *100, 2)
print("Percentage of women who survived:", rate_women)

men = df.loc[df.Sex == 'male']["Survived"]
rate_men = round(sum(men)/len(men) *100, 2)
print("Percentage of men who survived:", rate_men)

Percentage of women who survived: 74.2
Percentage of men who survived: 18.89

#Q3. How many children survived (under 18)?

In [73]:
children = df[df['Age'] < 18]
num_children_survived = len(children[children['Survived'] == 1])
print("Number of children who survived:", num_children_survived)

Number of children who survived: 61

#Q4. What percentage of passenger were in each class?

In [74]:
(df['Pclass'].value_counts(normalize=True) * 100).round(2)

Pclass
3    55.11
1    24.24
2    20.65
Name: proportion, dtype: float64

#Q5. Which embarkation port had the most passengers, and what was its survival rate?

In [75]:
print("Passenger counts by port:")
print(df['Embarked'].value_counts())

print("\nSurvival rate by port:")
print((df.groupby('Embarked')['Survived'].mean() * 100).round(2))

Passenger counts by port:
Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

Survival rate by port:
Embarked
C    55.36
Q    38.96
S    33.70
Name: Survived, dtype: float64

#Q6. Which class generated the most total fare revenue?

In [76]:
df.groupby('Pclass')['Fare'].sum().round(2)

Pclass
1    18177.41
2     3801.84
3     6714.70
Name: Fare, dtype: float64

#Q7. What was the average fare paid by the passangers who survived vs not survived?

In [77]:
avg_fare_survived = df[df['Survived'] == 1]['Fare'].mean().round(2)
avg_fare_not_survived = df[df['Survived'] == 0]['Fare'].mean().round(2)
overall_avg_fare = df['Fare'].mean().round(2)

print("Average fare (survived): $", avg_fare_survived)
print("Average fare (not survived): $", avg_fare_not_survived)
print("Overall average fare: $", overall_avg_fare)

Average fare (survived): $ 48.4
Average fare (not survived): $ 22.12
Overall average fare: $ 32.2

#Q8. How many passengers paid a fare greater than $100?

In [78]:
expensive_tickets = df[df["Fare"] > 100]

print("Passengers with Fare > $100:", len(expensive_tickets))

Passengers with Fare > $100: 53